# Generated by Django 2.0 on 2018-02-17 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='type',
            new_name='transport_type',
        ),
    ]
